/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.devicelendingandaccesstrackerapp;

import javax.swing.JOptionPane;

/**
 *
 * @author dhruv
 */
public class GUIApp extends javax.swing.JFrame {

    private Staff currentStaff;
    private Borrower currentBorrower;
    private SingleLinkedList deviceList;
    private SingleLinkedList borrowerList;
    private Queue loanQueue;
    private int loanCounter = 0;
    private Stack loginHistory; // Stack to keep track of who logged in (last login is on top)
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIApp.class.getName());

    /**
     * Creates new form GUIApp
     */
    public GUIApp() {
        initComponents();
        // Show only role-selection at startup; hide all other panels
        staffLoginForm.setVisible(false);
        borrowerLoginForm.setVisible(false);
        staffDashBoard.setVisible(false);
        borrowerDashboard.setVisible(false);
        dashBoard.setVisible(true);
        LoginSBtn.addActionListener(e -> handleStaffLogin());
        LoginBBtn.addActionListener(e -> handleBorrowerLogin());
        deviceList = new SingleLinkedList();
        borrowerList = new SingleLinkedList();
        loanQueue = new Queue();
        loginHistory = new Stack(); // create the login history stack
        lendDeviceSDBtn.addActionListener(e -> handleLendDevice());
        returnBDBtn.addActionListener(e -> handleReturnDevice());
        logOutBDBtn.addActionListener(e -> {
            dashBoard.setVisible(true);
            staffLoginForm.setVisible(false);
            borrowerLoginForm.setVisible(false);
            staffDashBoard.setVisible(false);
            borrowerDashboard.setVisible(false);
            currentStaff = null;
            currentBorrower = null;
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginRB = new javax.swing.ButtonGroup();
        dashBoard = new javax.swing.JPanel();
        titleDLbl = new javax.swing.JLabel();
        staffDRB = new javax.swing.JRadioButton();
        borrowerDRB = new javax.swing.JRadioButton();
        discDLbl = new javax.swing.JLabel();
        staffLoginForm = new javax.swing.JPanel();
        titleSLbl = new javax.swing.JLabel();
        staffIdSLbl = new javax.swing.JLabel();
        nameSLbl = new javax.swing.JLabel();
        emailSLbl = new javax.swing.JLabel();
        phoneSLbl = new javax.swing.JLabel();
        staffRoleSLbl = new javax.swing.JLabel();
        staffIdSTF = new javax.swing.JTextField();
        nameSTF = new javax.swing.JTextField();
        emailSTF = new javax.swing.JTextField();
        roleSTF = new javax.swing.JTextField();
        phoneSTF = new javax.swing.JTextField();
        discSLbl = new javax.swing.JLabel();
        backSBtn = new javax.swing.JButton();
        LoginSBtn = new javax.swing.JButton();
        borrowerLoginForm = new javax.swing.JPanel();
        titleBLbl = new javax.swing.JLabel();
        userIdBLbl = new javax.swing.JLabel();
        nameBLbl = new javax.swing.JLabel();
        emailBLbl = new javax.swing.JLabel();
        phoneBLbl = new javax.swing.JLabel();
        skillLevelBLbl = new javax.swing.JLabel();
        userIdBTF = new javax.swing.JTextField();
        nameBTF = new javax.swing.JTextField();
        emailBTF = new javax.swing.JTextField();
        skillLevelBTF = new javax.swing.JTextField();
        phoneBTF = new javax.swing.JTextField();
        discBLbl = new javax.swing.JLabel();
        backBBtn = new javax.swing.JButton();
        LoginBBtn = new javax.swing.JButton();
        staffDashBoard = new javax.swing.JPanel();
        titleSDLbl = new javax.swing.JLabel();
        devicePanel = new javax.swing.JPanel();
        devicesSDLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        deviceTableSD = new javax.swing.JTable();
        addSDBtn = new javax.swing.JButton();
        activeLoansPanel = new javax.swing.JPanel();
        activeLoansSDLbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        activeLoanTableSD = new javax.swing.JTable();
        lendDeviceSDBtn = new javax.swing.JButton();
        borrowerPanel = new javax.swing.JPanel();
        borrowersSDLbl = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        borrowersListSD = new javax.swing.JList<>();
        logoutSDBtn = new javax.swing.JButton();
        borrowerDashboard = new javax.swing.JPanel();
        titleBDLbl = new javax.swing.JLabel();
        loansPanel = new javax.swing.JPanel();
        loansBDLbl = new javax.swing.JLabel();
        loansTableBS = new javax.swing.JScrollPane();
        activeLoansBD = new javax.swing.JTable();
        availableDevicePanel = new javax.swing.JPanel();
        availableDeviceBDLbl = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        availableDeviceTableBD = new javax.swing.JTable();
        requestDeviceBDBtn = new javax.swing.JButton();
        logOutBDBtn = new javax.swing.JButton();
        returnBDBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        dashBoard.setBackground(new java.awt.Color(232, 244, 253));
        dashBoard.setPreferredSize(new java.awt.Dimension(508, 344));

        titleDLbl.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        titleDLbl.setForeground(new java.awt.Color(31, 45, 61));
        titleDLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleDLbl.setText("Device Lending & Access Tracker ");

        staffDRB.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        staffDRB.setForeground(new java.awt.Color(31, 45, 61));
        staffDRB.setText("Staff");
        staffDRB.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        staffDRB.setContentAreaFilled(false);
        staffDRB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        staffDRB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        staffDRB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/staff.png"))); // NOI18N
        staffDRB.setIconTextGap(5);
        staffDRB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        staffDRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffDRBActionPerformed(evt);
            }
        });

        borrowerDRB.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        borrowerDRB.setForeground(new java.awt.Color(31, 45, 61));
        borrowerDRB.setText("Borrower");
        borrowerDRB.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        borrowerDRB.setContentAreaFilled(false);
        borrowerDRB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        borrowerDRB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        borrowerDRB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/borrower.png"))); // NOI18N
        borrowerDRB.setIconTextGap(5);
        borrowerDRB.setMaximumSize(new java.awt.Dimension(50, 76));
        borrowerDRB.setMinimumSize(new java.awt.Dimension(50, 76));
        borrowerDRB.setPreferredSize(new java.awt.Dimension(50, 76));
        borrowerDRB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        borrowerDRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowerDRBActionPerformed(evt);
            }
        });

        discDLbl.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        discDLbl.setForeground(new java.awt.Color(107, 124, 147));
        discDLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        discDLbl.setText("Select your role to continue");

        javax.swing.GroupLayout dashBoardLayout = new javax.swing.GroupLayout(dashBoard);
        dashBoard.setLayout(dashBoardLayout);
        dashBoardLayout.setHorizontalGroup(
            dashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashBoardLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(staffDRB, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(borrowerDRB, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(dashBoardLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(discDLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashBoardLayout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(titleDLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        dashBoardLayout.setVerticalGroup(
            dashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashBoardLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(titleDLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(discDLbl)
                .addGap(78, 78, 78)
                .addGroup(dashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(staffDRB, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrowerDRB, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        staffLoginForm.setBackground(new java.awt.Color(232, 244, 253));
        staffLoginForm.setPreferredSize(new java.awt.Dimension(508, 344));

        titleSLbl.setBackground(new java.awt.Color(31, 45, 61));
        titleSLbl.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        titleSLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleSLbl.setText("Staff Login");

        staffIdSLbl.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        staffIdSLbl.setText("Staff ID:");

        nameSLbl.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        nameSLbl.setText("Name:");

        emailSLbl.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        emailSLbl.setText("Email:");

        phoneSLbl.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        phoneSLbl.setText("Phone:");

        staffRoleSLbl.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        staffRoleSLbl.setText("Staff Role:");

        discSLbl.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        discSLbl.setForeground(new java.awt.Color(107, 124, 147));
        discSLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        discSLbl.setText("Enter your Staff Credentials");

        backSBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        backSBtn.setForeground(new java.awt.Color(31, 45, 61));
        backSBtn.setText("Back ");
        backSBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backSBtnActionPerformed(evt);
            }
        });

        LoginSBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LoginSBtn.setForeground(new java.awt.Color(31, 45, 61));
        LoginSBtn.setText("Login");

        javax.swing.GroupLayout staffLoginFormLayout = new javax.swing.GroupLayout(staffLoginForm);
        staffLoginForm.setLayout(staffLoginFormLayout);
        staffLoginFormLayout.setHorizontalGroup(
            staffLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffLoginFormLayout.createSequentialGroup()
                .addGroup(staffLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(staffLoginFormLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(staffLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(staffRoleSLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(phoneSLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(emailSLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nameSLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(staffIdSLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(staffLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(staffIdSTF)
                            .addComponent(nameSTF)
                            .addComponent(emailSTF)
                            .addComponent(phoneSTF, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(roleSTF)))
                    .addGroup(staffLoginFormLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(titleSLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(staffLoginFormLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(discSLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(staffLoginFormLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(backSBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LoginSBtn)
                .addGap(103, 103, 103))
        );
        staffLoginFormLayout.setVerticalGroup(
            staffLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffLoginFormLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(titleSLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(discSLbl)
                .addGap(42, 42, 42)
                .addGroup(staffLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(staffIdSLbl)
                    .addComponent(staffIdSTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(staffLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nameSLbl)
                    .addComponent(nameSTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(staffLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailSLbl)
                    .addComponent(emailSTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(staffLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(phoneSLbl)
                    .addComponent(phoneSTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(staffLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(staffRoleSLbl)
                    .addComponent(roleSTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(staffLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backSBtn)
                    .addComponent(LoginSBtn))
                .addContainerGap(219, Short.MAX_VALUE))
        );

        borrowerLoginForm.setBackground(new java.awt.Color(232, 244, 253));
        borrowerLoginForm.setPreferredSize(new java.awt.Dimension(508, 344));

        titleBLbl.setBackground(new java.awt.Color(31, 45, 61));
        titleBLbl.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        titleBLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleBLbl.setText("Borrower Login");

        userIdBLbl.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        userIdBLbl.setText("User ID:");

        nameBLbl.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        nameBLbl.setText("Name:");

        emailBLbl.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        emailBLbl.setText("Email:");

        phoneBLbl.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        phoneBLbl.setText("Phone:");

        skillLevelBLbl.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        skillLevelBLbl.setText("Skill Level:");

        nameBTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameBTFActionPerformed(evt);
            }
        });

        discBLbl.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        discBLbl.setForeground(new java.awt.Color(107, 124, 147));
        discBLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        discBLbl.setText("Enter your credentials");

        backBBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        backBBtn.setForeground(new java.awt.Color(31, 45, 61));
        backBBtn.setText("Back ");
        backBBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBBtnActionPerformed(evt);
            }
        });

        LoginBBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LoginBBtn.setForeground(new java.awt.Color(31, 45, 61));
        LoginBBtn.setText("Login");

        javax.swing.GroupLayout borrowerLoginFormLayout = new javax.swing.GroupLayout(borrowerLoginForm);
        borrowerLoginForm.setLayout(borrowerLoginFormLayout);
        borrowerLoginFormLayout.setHorizontalGroup(
            borrowerLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borrowerLoginFormLayout.createSequentialGroup()
                .addGroup(borrowerLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(borrowerLoginFormLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(borrowerLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(titleBLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(discBLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(borrowerLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, borrowerLoginFormLayout.createSequentialGroup()
                            .addGap(76, 76, 76)
                            .addComponent(backBBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                            .addComponent(LoginBBtn))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, borrowerLoginFormLayout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addGroup(borrowerLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(phoneBLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(emailBLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nameBLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(userIdBLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(skillLevelBLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(borrowerLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(userIdBTF)
                                .addComponent(nameBTF)
                                .addComponent(emailBTF)
                                .addComponent(phoneBTF, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                .addComponent(skillLevelBTF)))))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        borrowerLoginFormLayout.setVerticalGroup(
            borrowerLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borrowerLoginFormLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(titleBLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(discBLbl)
                .addGap(42, 42, 42)
                .addGroup(borrowerLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userIdBLbl)
                    .addComponent(userIdBTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(borrowerLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nameBLbl)
                    .addComponent(nameBTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(borrowerLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailBLbl)
                    .addComponent(emailBTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(borrowerLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(phoneBLbl)
                    .addComponent(phoneBTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(borrowerLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(skillLevelBLbl)
                    .addComponent(skillLevelBTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(borrowerLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBBtn)
                    .addComponent(LoginBBtn))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        staffDashBoard.setBackground(new java.awt.Color(232, 244, 253));

        titleSDLbl.setBackground(new java.awt.Color(31, 45, 61));
        titleSDLbl.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        titleSDLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleSDLbl.setText("Staff Dashboard");

        devicePanel.setBackground(new java.awt.Color(255, 255, 255));

        devicesSDLbl.setBackground(new java.awt.Color(31, 45, 61));
        devicesSDLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        devicesSDLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        devicesSDLbl.setText("Devices");

        deviceTableSD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Device ID", "Device Name", "Status", "Loaned to"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(deviceTableSD);

        addSDBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addSDBtn.setText("Add Device");
        addSDBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSDBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout devicePanelLayout = new javax.swing.GroupLayout(devicePanel);
        devicePanel.setLayout(devicePanelLayout);
        devicePanelLayout.setHorizontalGroup(
            devicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(devicePanelLayout.createSequentialGroup()
                .addGroup(devicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, devicePanelLayout.createSequentialGroup()
                        .addContainerGap(16, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(devicePanelLayout.createSequentialGroup()
                        .addGroup(devicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(devicePanelLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(devicesSDLbl))
                            .addGroup(devicePanelLayout.createSequentialGroup()
                                .addGap(175, 175, 175)
                                .addComponent(addSDBtn)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        devicePanelLayout.setVerticalGroup(
            devicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(devicePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(devicesSDLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addSDBtn)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        activeLoansPanel.setBackground(new java.awt.Color(255, 255, 255));

        activeLoansSDLbl.setBackground(new java.awt.Color(31, 45, 61));
        activeLoansSDLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        activeLoansSDLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        activeLoansSDLbl.setText("Active Loans");

        activeLoanTableSD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Device", "Borrower", "Due Date"
            }
        ));
        jScrollPane2.setViewportView(activeLoanTableSD);

        lendDeviceSDBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lendDeviceSDBtn.setText("Lend Device");

        javax.swing.GroupLayout activeLoansPanelLayout = new javax.swing.GroupLayout(activeLoansPanel);
        activeLoansPanel.setLayout(activeLoansPanelLayout);
        activeLoansPanelLayout.setHorizontalGroup(
            activeLoansPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activeLoansPanelLayout.createSequentialGroup()
                .addGroup(activeLoansPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(activeLoansPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(activeLoansSDLbl))
                    .addGroup(activeLoansPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(activeLoansPanelLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(lendDeviceSDBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        activeLoansPanelLayout.setVerticalGroup(
            activeLoansPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activeLoansPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(activeLoansSDLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lendDeviceSDBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        borrowerPanel.setBackground(new java.awt.Color(255, 255, 255));

        borrowersSDLbl.setBackground(new java.awt.Color(31, 45, 61));
        borrowersSDLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        borrowersSDLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        borrowersSDLbl.setText("Borrowers");

        jScrollPane3.setViewportView(borrowersListSD);

        javax.swing.GroupLayout borrowerPanelLayout = new javax.swing.GroupLayout(borrowerPanel);
        borrowerPanel.setLayout(borrowerPanelLayout);
        borrowerPanelLayout.setHorizontalGroup(
            borrowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borrowerPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(borrowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(borrowersSDLbl)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        borrowerPanelLayout.setVerticalGroup(
            borrowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borrowerPanelLayout.createSequentialGroup()
                .addComponent(borrowersSDLbl)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        logoutSDBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logoutSDBtn.setText("Log Out");
        logoutSDBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutSDBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout staffDashBoardLayout = new javax.swing.GroupLayout(staffDashBoard);
        staffDashBoard.setLayout(staffDashBoardLayout);
        staffDashBoardLayout.setHorizontalGroup(
            staffDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffDashBoardLayout.createSequentialGroup()
                .addGroup(staffDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(staffDashBoardLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(staffDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(borrowerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(staffDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(devicePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(activeLoansPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addGroup(staffDashBoardLayout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(titleSDLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutSDBtn)))
                .addContainerGap())
        );
        staffDashBoardLayout.setVerticalGroup(
            staffDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffDashBoardLayout.createSequentialGroup()
                .addGroup(staffDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(staffDashBoardLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titleSDLbl))
                    .addComponent(logoutSDBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(devicePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(activeLoansPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(borrowerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        borrowerDashboard.setBackground(new java.awt.Color(232, 244, 253));

        titleBDLbl.setBackground(new java.awt.Color(31, 45, 61));
        titleBDLbl.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        titleBDLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleBDLbl.setText("Borrower Dashboard");
        titleBDLbl.setPreferredSize(new java.awt.Dimension(171, 30));

        loansPanel.setBackground(new java.awt.Color(255, 255, 255));
        loansPanel.setMinimumSize(new java.awt.Dimension(0, 0));

        loansBDLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loansBDLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loansBDLbl.setText("My Active Loans");

        activeLoansBD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Loan ID", "Device", "Start Date", "Due Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        loansTableBS.setViewportView(activeLoansBD);

        javax.swing.GroupLayout loansPanelLayout = new javax.swing.GroupLayout(loansPanel);
        loansPanel.setLayout(loansPanelLayout);
        loansPanelLayout.setHorizontalGroup(
            loansPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loansPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(loansPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loansTableBS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loansBDLbl))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loansPanelLayout.setVerticalGroup(
            loansPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loansPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loansBDLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loansTableBS, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        availableDevicePanel.setBackground(new java.awt.Color(255, 255, 255));
        availableDevicePanel.setMinimumSize(new java.awt.Dimension(0, 0));

        availableDeviceBDLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        availableDeviceBDLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        availableDeviceBDLbl.setText("Available Devices");

        availableDeviceTableBD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Device ID", "Device Type", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(availableDeviceTableBD);

        javax.swing.GroupLayout availableDevicePanelLayout = new javax.swing.GroupLayout(availableDevicePanel);
        availableDevicePanel.setLayout(availableDevicePanelLayout);
        availableDevicePanelLayout.setHorizontalGroup(
            availableDevicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(availableDevicePanelLayout.createSequentialGroup()
                .addGroup(availableDevicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(availableDevicePanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(availableDeviceBDLbl))
                    .addGroup(availableDevicePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        availableDevicePanelLayout.setVerticalGroup(
            availableDevicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(availableDevicePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(availableDeviceBDLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        requestDeviceBDBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        requestDeviceBDBtn.setText("Request Device");
        requestDeviceBDBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestDeviceBDBtnActionPerformed(evt);
            }
        });

        logOutBDBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logOutBDBtn.setText("Log Out");

        returnBDBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        returnBDBtn.setText("Return Device");

        javax.swing.GroupLayout borrowerDashboardLayout = new javax.swing.GroupLayout(borrowerDashboard);
        borrowerDashboard.setLayout(borrowerDashboardLayout);
        borrowerDashboardLayout.setHorizontalGroup(
            borrowerDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borrowerDashboardLayout.createSequentialGroup()
                .addGroup(borrowerDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, borrowerDashboardLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(titleBDLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logOutBDBtn))
                    .addGroup(borrowerDashboardLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(availableDevicePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(borrowerDashboardLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(loansPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(borrowerDashboardLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(requestDeviceBDBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(returnBDBtn)
                        .addGap(28, 28, 28)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        borrowerDashboardLayout.setVerticalGroup(
            borrowerDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borrowerDashboardLayout.createSequentialGroup()
                .addGroup(borrowerDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(borrowerDashboardLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(titleBDLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(logOutBDBtn))
                .addGap(47, 47, 47)
                .addComponent(loansPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(availableDevicePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(borrowerDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(requestDeviceBDBtn)
                    .addComponent(returnBDBtn))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(staffLoginForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(borrowerLoginForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(staffDashBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(borrowerDashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(staffLoginForm, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 113, Short.MAX_VALUE)
                    .addComponent(borrowerLoginForm, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(staffDashBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(borrowerDashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void handleStaffLogin() {
        String userId = staffIdSTF.getText().trim();
        String name = nameSTF.getText().trim();
        String email = emailSTF.getText().trim();
        String phone = phoneSTF.getText().trim();
        String staffRole = roleSTF.getText().trim();
        if (userId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Staff ID is required.", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Name is required.", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Email is required.", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!email.contains("@")) {
            JOptionPane.showMessageDialog(this, "Email must contain @.", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!phone.isEmpty() && !phone.matches("[0-9]+")) {
            JOptionPane.showMessageDialog(this, "Phone must contain only digits (0-9).", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!phone.isEmpty() && phone.length() != 10) {
            JOptionPane.showMessageDialog(this, "Phone must be 10 digits long.", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }
        currentStaff = new Staff(userId, name, email, phone, staffRole);
        currentBorrower = null;
        // Push this login event to the login history stack
        loginHistory.push(name + " (Staff) logged in");
        JOptionPane.showMessageDialog(this, "Welcome, " + name + " (Staff).");
        dashBoard.setVisible(false);
        staffLoginForm.setVisible(false);
        borrowerLoginForm.setVisible(false);
        staffDashBoard.setVisible(true);
        borrowerDashboard.setVisible(false);
        
        // Refresh the borrowers JList when staff dashboard opens
        javax.swing.DefaultListModel<String> listModel = new javax.swing.DefaultListModel<>();
        for (int i = 0; i < borrowerList.size(); i++) {
            Borrower b = (Borrower) borrowerList.get(i);
            listModel.addElement(b.getName());
        }
        borrowersListSD.setModel(listModel);
    }

    private void handleBorrowerLogin() {
        String userId = userIdBTF.getText().trim();
        String name = nameBTF.getText().trim();
        String email = emailBTF.getText().trim();
        String phone = phoneBTF.getText().trim();
        String skillLevel = skillLevelBTF.getText().trim();
        if (userId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "User ID is required.", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Name is required.", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Email is required.", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!email.contains("@")) {
            JOptionPane.showMessageDialog(this, "Email must contain @.", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!phone.isEmpty() && !phone.matches("[0-9]+")) {
            JOptionPane.showMessageDialog(this, "Phone must contain only digits (0-9).", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!phone.isEmpty() && phone.length() != 10) {
            JOptionPane.showMessageDialog(this, "Phone must be 10 digits long.", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int maxActiveLoan = 3;
        try {
            if (!skillLevel.isEmpty()) {
                maxActiveLoan = Math.max(1, Integer.parseInt(skillLevel));
            }
        } catch (NumberFormatException ex) {
        }
        currentBorrower = new Borrower(userId, name, email, phone, skillLevel, maxActiveLoan);
        currentStaff = null;
        borrowerList.add(currentBorrower);
        
        // Refresh the borrowers JList so staff can see all borrowers
        javax.swing.DefaultListModel<String> listModel = new javax.swing.DefaultListModel<>();
        for (int i = 0; i < borrowerList.size(); i++) {
            Borrower b = (Borrower) borrowerList.get(i);
            listModel.addElement(b.getName());
        }
        borrowersListSD.setModel(listModel);
        
        // Push this login event to the login history stack
        loginHistory.push(name + " (Borrower) logged in");
        JOptionPane.showMessageDialog(this, "Welcome, " + name + " (Borrower).");
        dashBoard.setVisible(false);
        staffLoginForm.setVisible(false);
        borrowerLoginForm.setVisible(false);
        staffDashBoard.setVisible(false);
        borrowerDashboard.setVisible(true);

        // Populate "My Active Loans" table — show only loans belonging to this borrower
        javax.swing.table.DefaultTableModel loansModel =
            (javax.swing.table.DefaultTableModel) activeLoansBD.getModel();
        loansModel.setRowCount(0);
        Queue tempQueue = new Queue();
        while (!loanQueue.isEmpty()) {
            Loan loan = (Loan) loanQueue.dequeue();
            if (loan.getBorrower().equals(name)) {
                loansModel.addRow(new Object[]{ loan.getLoanId(), loan.getDevice(), loan.getStartDate(), loan.getDueDate() });
            }
            tempQueue.enqueue(loan);
        }
        while (!tempQueue.isEmpty()) {
            loanQueue.enqueue(tempQueue.dequeue());
        }

        // Populate "Available Devices" table — show only devices with status "Available"
        javax.swing.table.DefaultTableModel availModel =
            (javax.swing.table.DefaultTableModel) availableDeviceTableBD.getModel();
        availModel.setRowCount(0);
        for (int i = 0; i < deviceList.size(); i++) {
            Device d = (Device) deviceList.get(i);
            if (d.getStatus().equals("Available")) {
                availModel.addRow(new Object[]{ d.getDeviceId(), d.getType(), d.getStatus() });
            }
        }
    }
    private void staffDRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffDRBActionPerformed
        dashBoard.setVisible(false);
        staffLoginForm.setVisible(true);
        borrowerLoginForm.setVisible(false);
        staffDashBoard.setVisible(false);
        borrowerDashboard.setVisible(false);
    }//GEN-LAST:event_staffDRBActionPerformed

    private void nameBTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameBTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameBTFActionPerformed

    private void borrowerDRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowerDRBActionPerformed
        dashBoard.setVisible(false);
        staffLoginForm.setVisible(false);
        borrowerLoginForm.setVisible(true);
        staffDashBoard.setVisible(false);
        borrowerDashboard.setVisible(false);
    }//GEN-LAST:event_borrowerDRBActionPerformed

    private void backSBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backSBtnActionPerformed
        dashBoard.setVisible(true);
        staffLoginForm.setVisible(false);
        borrowerLoginForm.setVisible(false);
        staffDashBoard.setVisible(false);
        borrowerDashboard.setVisible(false);
    }//GEN-LAST:event_backSBtnActionPerformed

    private void backBBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBBtnActionPerformed
        dashBoard.setVisible(true);
        staffLoginForm.setVisible(false);
        borrowerLoginForm.setVisible(false);
        staffDashBoard.setVisible(false);
        borrowerDashboard.setVisible(false);
    }//GEN-LAST:event_backBBtnActionPerformed

    // This method runs when the "Add Device" button is clicked
    private void addSDBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSDBtnActionPerformed

        // Ask the user to enter a Device ID
        String deviceId = JOptionPane.showInputDialog(this, "Enter Device ID:");

        // If user clicked Cancel (null) or left it empty, show a warning and stop
        if (deviceId == null || deviceId.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Device ID is required.", "Validation", JOptionPane.WARNING_MESSAGE);
            return;  // stop here, don't continue
        }

        //  Ask for the type of device (e.g. Laptop, Tablet, Phone)
        String type = JOptionPane.showInputDialog(this, "Enter Device Type (e.g. Laptop, Tablet):");
        if (type == null || type.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Device Type is required.", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }

        //  Ask for optional notes
        String notes = JOptionPane.showInputDialog(this, "Enter Notes (optional):");
        if (notes == null) {
            notes = "";  // if user clicked Cancel, just set notes to empty
        }

        //Create a new Device object with status "Available"
        Device device = new Device(deviceId.trim(), type.trim(), "Available", notes.trim());

        //  Add the device to our SingleLinkedList 
        deviceList.add(device);

        //  Refresh the devices table on screen
        // Get the table model so we can change the rows
        javax.swing.table.DefaultTableModel model
                = (javax.swing.table.DefaultTableModel) deviceTableSD.getModel();

        // Clear all old rows from the table
        model.setRowCount(0);

        // Loop through every device in the linked list and add it as a row
        for (int i = 0; i < deviceList.size(); i++) {
            Device d = (Device) deviceList.get(i);  // get device from list (cast Object to Device)
            model.addRow(new Object[]{d.getDeviceId(), d.getType(), d.getStatus(), d.getNotes()});
        }
    }//GEN-LAST:event_addSDBtnActionPerformed

    // This method runs when the "Log Out" button is clicked on the Staff Dashboard
    private void logoutSDBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutSDBtnActionPerformed
        // Show the role selection screen and hide everything else
        dashBoard.setVisible(true);
        staffLoginForm.setVisible(false);
        borrowerLoginForm.setVisible(false);
        staffDashBoard.setVisible(false);
        borrowerDashboard.setVisible(false);
        // Clear the logged-in user
        currentStaff = null;
        currentBorrower = null;
    }//GEN-LAST:event_logoutSDBtnActionPerformed

    // This method runs when the "Request Device" button is clicked on the Borrower Dashboard
    private void requestDeviceBDBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestDeviceBDBtnActionPerformed

        // Check if there are any devices at all
        if (deviceList.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No devices available.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        //Ask the borrower to type the Device ID they want
        String deviceId = JOptionPane.showInputDialog(this, "Enter the Device ID you want to request:");
        if (deviceId == null || deviceId.trim().isEmpty()) {
            return;
        }
        deviceId = deviceId.trim();

        //  Search for the device in the list
        Device foundDevice = null;
        for (int i = 0; i < deviceList.size(); i++) {
            Device d = (Device) deviceList.get(i);
            if (d.getDeviceId().equals(deviceId)) {
                foundDevice = d;
                break;
            }
        }

        //If device not found, show error
        if (foundDevice == null) {
            JOptionPane.showMessageDialog(this, "Device not found.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        //  If device is already loaned, show error
        if (foundDevice.getStatus().equals("Loaned")) {
            JOptionPane.showMessageDialog(this, "This device is already loaned out.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        //  Ask for start date
        String startDate = JOptionPane.showInputDialog(this, "Enter Start Date (e.g. 05-03-2026):");
        if (startDate == null || startDate.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Start Date is required.", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }
        startDate = startDate.trim();

        //  Ask for due date
        String dueDate = JOptionPane.showInputDialog(this, "Enter Due Date (e.g. 20-03-2026):");
        if (dueDate == null || dueDate.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Due Date is required.", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }
        dueDate = dueDate.trim();

        // Update the device status to Loaned
        foundDevice.setStatus("Loaned");
        foundDevice.setNotes(currentBorrower.getName());

        //Create a loan ID and the Loan object, then add to queue
        loanCounter = loanCounter + 1;
        String loanId = "L" + loanCounter;
        Loan loan = new Loan(loanId, currentBorrower.getName(), deviceId, startDate, dueDate, "Active");
        loanQueue.enqueue(loan);

        //  Refresh "My Active Loans" table
        javax.swing.table.DefaultTableModel loansModel =
            (javax.swing.table.DefaultTableModel) activeLoansBD.getModel();
        loansModel.setRowCount(0);
        Queue tempQueue = new Queue();
        while (!loanQueue.isEmpty()) {
            Loan l = (Loan) loanQueue.dequeue();
            if (l.getBorrower().equals(currentBorrower.getName())) {
                loansModel.addRow(new Object[]{ l.getLoanId(), l.getDevice(), l.getStartDate(), l.getDueDate() });
            }
            tempQueue.enqueue(l);
        }
        while (!tempQueue.isEmpty()) {
            loanQueue.enqueue(tempQueue.dequeue());
        }

        // Refresh "Available Devices" table
        javax.swing.table.DefaultTableModel availModel =
            (javax.swing.table.DefaultTableModel) availableDeviceTableBD.getModel();
        availModel.setRowCount(0);
        for (int i = 0; i < deviceList.size(); i++) {
            Device d = (Device) deviceList.get(i);
            if (d.getStatus().equals("Available")) {
                availModel.addRow(new Object[]{ d.getDeviceId(), d.getType(), d.getStatus() });
            }
        }

        //  Show success message
        JOptionPane.showMessageDialog(this, "Device " + deviceId + " requested successfully!");
    }//GEN-LAST:event_requestDeviceBDBtnActionPerformed

    // This method runs when the "Return Device" button is clicked on the Borrower Dashboard
    private void handleReturnDevice() {

        //  Make sure the borrower is logged in
        if (currentBorrower == null) {
            JOptionPane.showMessageDialog(this, "No borrower logged in.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Ask the borrower which Device ID they want to return
        String deviceId = JOptionPane.showInputDialog(this, "Enter the Device ID you want to return:");
        if (deviceId == null || deviceId.trim().isEmpty()) {
            return; // user clicked Cancel
        }
        deviceId = deviceId.trim();

        //  Search the loan queue for a matching loan (same device + same borrower)
        Loan foundLoan = null;
        Queue tempQueue = new Queue();

        while (!loanQueue.isEmpty()) {
            Loan l = (Loan) loanQueue.dequeue();
            // Check if this loan belongs to the current borrower and matches the device ID
            if (l.getDevice().equals(deviceId) && l.getBorrower().equals(currentBorrower.getName())) {
                foundLoan = l; // found the loan
            } else {
                tempQueue.enqueue(l); // keep all other loans
            }
        }

        // Put all the kept loans back into the main queue
        while (!tempQueue.isEmpty()) {
            loanQueue.enqueue(tempQueue.dequeue());
        }

        // If no matching loan was found, show error
        if (foundLoan == null) {
            JOptionPane.showMessageDialog(this, "No active loan found for Device ID: " + deviceId, "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        //  Find the device in the device list and set it back to "Available"
        for (int i = 0; i < deviceList.size(); i++) {
            Device d = (Device) deviceList.get(i);
            if (d.getDeviceId().equals(deviceId)) {
                d.setStatus("Available"); // mark device as available again
                d.setNotes("");           // clear the borrower name from notes
                break;
            }
        }

        // Refresh "My Active Loans" table
        javax.swing.table.DefaultTableModel loansModel =
            (javax.swing.table.DefaultTableModel) activeLoansBD.getModel();
        loansModel.setRowCount(0); // clear the table
        Queue tempQueue2 = new Queue();
        while (!loanQueue.isEmpty()) {
            Loan l = (Loan) loanQueue.dequeue();
            if (l.getBorrower().equals(currentBorrower.getName())) {
                loansModel.addRow(new Object[]{ l.getLoanId(), l.getDevice(), l.getStartDate(), l.getDueDate() });
            }
            tempQueue2.enqueue(l);
        }
        while (!tempQueue2.isEmpty()) {
            loanQueue.enqueue(tempQueue2.dequeue());
        }

        //  Refresh "Available Devices" table 
        javax.swing.table.DefaultTableModel availModel =
            (javax.swing.table.DefaultTableModel) availableDeviceTableBD.getModel();
        availModel.setRowCount(0); // clear the table
        for (int i = 0; i < deviceList.size(); i++) {
            Device d = (Device) deviceList.get(i);
            if (d.getStatus().equals("Available")) {
                availModel.addRow(new Object[]{ d.getDeviceId(), d.getType(), d.getStatus() });
            }
        }

        //  Show success message
        JOptionPane.showMessageDialog(this, "Device " + deviceId + " returned successfully!");
    }

    // This method runs when the "Lend Device" button is clicked
    private void handleLendDevice() {

        //  Check if the device list is empty — can't lend if no devices exist
        if (deviceList.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No devices available. Add a device first.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        //  Ask the user to type the Device ID they want to lend
        String selectedDevice = JOptionPane.showInputDialog(this, "Enter the Device ID to lend:");
        if (selectedDevice == null || selectedDevice.trim().isEmpty()) {
            return;  // user cancelled
        }
        selectedDevice = selectedDevice.trim();

        //  Search for the device in our SingleLinkedList
        // We loop through the list and compare each device's ID
        Device foundDevice = null;
        for (int i = 0; i < deviceList.size(); i++) {
            Device d = (Device) deviceList.get(i);  // get device at index i
            if (d.getDeviceId().equals(selectedDevice)) {
                foundDevice = d;  // found it!
                break;  // stop searching
            }
        }

        //  If we didn't find the device, show error
        if (foundDevice == null) {
            JOptionPane.showMessageDialog(this, "Device not found.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // If the device is already loaned out, show error
        if (foundDevice.getStatus().equals("Loaned")) {
            JOptionPane.showMessageDialog(this, "This device is already loaned out.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        //  Ask for borrower name
        String borrowerName = JOptionPane.showInputDialog(this, "Enter Borrower Name:");
        if (borrowerName == null || borrowerName.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Borrower Name is required.", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }
        borrowerName = borrowerName.trim();

        // Ask for the start date of the loan
        String startDate = JOptionPane.showInputDialog(this, "Enter Start Date (e.g. 05-03-2026):");
        if (startDate == null || startDate.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Start Date is required.", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }
        startDate = startDate.trim();

        //  Ask for the due date (when device should be returned)
        String dueDate = JOptionPane.showInputDialog(this, "Enter Due Date (e.g. 20-03-2026):");
        if (dueDate == null || dueDate.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Due Date is required.", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }
        dueDate = dueDate.trim();

        //  Update the device — change status to "Loaned" and store who borrowed it
        foundDevice.setStatus("Loaned");
        foundDevice.setNotes(borrowerName);

        //  Create a unique loan ID using a simple counter (L1, L2, L3...)
        loanCounter = loanCounter + 1;
        String loanId = "L" + loanCounter;

        //  Create a new Loan object and add it to the Queue 
        Loan loan = new Loan(loanId, borrowerName, selectedDevice, startDate, dueDate, "Active");
        loanQueue.enqueue(loan);  // enqueue = add to the back of the queue

        // Refresh the devices table to show updated status
        javax.swing.table.DefaultTableModel deviceModel
                = (javax.swing.table.DefaultTableModel) deviceTableSD.getModel();
        deviceModel.setRowCount(0);  // clear all rows
        for (int i = 0; i < deviceList.size(); i++) {
            Device d = (Device) deviceList.get(i);
            deviceModel.addRow(new Object[]{d.getDeviceId(), d.getType(), d.getStatus(), d.getNotes()});
        }

        // Refresh the active loans table
        refreshLoanTable();

        // Show success message
        JOptionPane.showMessageDialog(this, "Device " + selectedDevice + " loaned to " + borrowerName + ".");
    }

    // This method refreshes the Active Loans table
    // Since Queue only lets us access the front, we have to take items out and put them back
    private void refreshLoanTable() {

        // Get the table model so we can change the rows
        javax.swing.table.DefaultTableModel loanModel
                = (javax.swing.table.DefaultTableModel) activeLoanTableSD.getModel();

        // Clear all old rows
        loanModel.setRowCount(0);

        // We need a temporary queue to hold loans while we read them
        Queue tempQueue = new Queue();

        // Take each loan out of the queue one by one (dequeue = remove from front)
        while (!loanQueue.isEmpty()) {
            Loan loan = (Loan) loanQueue.dequeue();  // remove from front of queue

            // Add this loan as a row in the table
            loanModel.addRow(new Object[]{loan.getDevice(), loan.getBorrower(), loan.getDueDate()});

            // Save the loan in our temporary queue so we don't lose it
            tempQueue.enqueue(loan);
        }

        // Now put all loans back into the original queue from the temp queue
        while (!tempQueue.isEmpty()) {
            loanQueue.enqueue(tempQueue.dequeue());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIApp().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginBBtn;
    private javax.swing.JButton LoginSBtn;
    private javax.swing.JTable activeLoanTableSD;
    private javax.swing.JTable activeLoansBD;
    private javax.swing.JPanel activeLoansPanel;
    private javax.swing.JLabel activeLoansSDLbl;
    private javax.swing.JButton addSDBtn;
    private javax.swing.JLabel availableDeviceBDLbl;
    private javax.swing.JPanel availableDevicePanel;
    private javax.swing.JTable availableDeviceTableBD;
    private javax.swing.JButton backBBtn;
    private javax.swing.JButton backSBtn;
    private javax.swing.JRadioButton borrowerDRB;
    private javax.swing.JPanel borrowerDashboard;
    private javax.swing.JPanel borrowerLoginForm;
    private javax.swing.JPanel borrowerPanel;
    private javax.swing.JList<String> borrowersListSD;
    private javax.swing.JLabel borrowersSDLbl;
    private javax.swing.JPanel dashBoard;
    private javax.swing.JPanel devicePanel;
    private javax.swing.JTable deviceTableSD;
    private javax.swing.JLabel devicesSDLbl;
    private javax.swing.JLabel discBLbl;
    private javax.swing.JLabel discDLbl;
    private javax.swing.JLabel discSLbl;
    private javax.swing.JLabel emailBLbl;
    private javax.swing.JTextField emailBTF;
    private javax.swing.JLabel emailSLbl;
    private javax.swing.JTextField emailSTF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton lendDeviceSDBtn;
    private javax.swing.JLabel loansBDLbl;
    private javax.swing.JPanel loansPanel;
    private javax.swing.JScrollPane loansTableBS;
    private javax.swing.JButton logOutBDBtn;
    private javax.swing.ButtonGroup loginRB;
    private javax.swing.JButton logoutSDBtn;
    private javax.swing.JLabel nameBLbl;
    private javax.swing.JTextField nameBTF;
    private javax.swing.JLabel nameSLbl;
    private javax.swing.JTextField nameSTF;
    private javax.swing.JLabel phoneBLbl;
    private javax.swing.JTextField phoneBTF;
    private javax.swing.JLabel phoneSLbl;
    private javax.swing.JTextField phoneSTF;
    private javax.swing.JButton requestDeviceBDBtn;
    private javax.swing.JButton returnBDBtn;
    private javax.swing.JTextField roleSTF;
    private javax.swing.JLabel skillLevelBLbl;
    private javax.swing.JTextField skillLevelBTF;
    private javax.swing.JRadioButton staffDRB;
    private javax.swing.JPanel staffDashBoard;
    private javax.swing.JLabel staffIdSLbl;
    private javax.swing.JTextField staffIdSTF;
    private javax.swing.JPanel staffLoginForm;
    private javax.swing.JLabel staffRoleSLbl;
    private javax.swing.JLabel titleBDLbl;
    private javax.swing.JLabel titleBLbl;
    private javax.swing.JLabel titleDLbl;
    private javax.swing.JLabel titleSDLbl;
    private javax.swing.JLabel titleSLbl;
    private javax.swing.JLabel userIdBLbl;
    private javax.swing.JTextField userIdBTF;
    // End of variables declaration//GEN-END:variables
}
