/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.devicelendingandaccesstrackerapp;

import javax.swing.JOptionPane;

/**
 *
 * @author dhruv
 */
public class GUIApp extends javax.swing.JFrame {

    private Staff currentStaff;
    private Borrower currentBorrower;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIApp.class.getName());

    /**
     * Creates new form GUIApp
     */
    public GUIApp() {
        initComponents();
        // Show only role-selection at startup; hide login forms until user picks a role
        staffLoginForm.setVisible(false);
        borrowerLoginForm.setVisible(false);
        dashBoard.setVisible(true);
        LoginSBtn.addActionListener(e -> handleStaffLogin());
        LoginBBtn.addActionListener(e -> handleBorrowerLogin());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginRB = new javax.swing.ButtonGroup();
        dashBoard = new javax.swing.JPanel();
        titleDLbl = new javax.swing.JLabel();
        staffDRB = new javax.swing.JRadioButton();
        borrowerDRB = new javax.swing.JRadioButton();
        discDLbl = new javax.swing.JLabel();
        staffLoginForm = new javax.swing.JPanel();
        titleSLbl = new javax.swing.JLabel();
        staffIdSLbl = new javax.swing.JLabel();
        nameSLbl = new javax.swing.JLabel();
        emailSLbl = new javax.swing.JLabel();
        phoneSLbl = new javax.swing.JLabel();
        staffRoleSLbl = new javax.swing.JLabel();
        staffIdSTF = new javax.swing.JTextField();
        nameSTF = new javax.swing.JTextField();
        emailSTF = new javax.swing.JTextField();
        roleSTF = new javax.swing.JTextField();
        phoneSTF = new javax.swing.JTextField();
        discSLbl = new javax.swing.JLabel();
        backSBtn = new javax.swing.JButton();
        LoginSBtn = new javax.swing.JButton();
        borrowerLoginForm = new javax.swing.JPanel();
        titleBLbl = new javax.swing.JLabel();
        userIdBLbl = new javax.swing.JLabel();
        nameBLbl = new javax.swing.JLabel();
        emailBLbl = new javax.swing.JLabel();
        phoneBLbl = new javax.swing.JLabel();
        skillLevelBLbl = new javax.swing.JLabel();
        userIdBTF = new javax.swing.JTextField();
        nameBTF = new javax.swing.JTextField();
        emailBTF = new javax.swing.JTextField();
        skillLevelBTF = new javax.swing.JTextField();
        phoneBTF = new javax.swing.JTextField();
        discBLbl = new javax.swing.JLabel();
        backBBtn = new javax.swing.JButton();
        LoginBBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        dashBoard.setBackground(new java.awt.Color(232, 244, 253));
        dashBoard.setPreferredSize(new java.awt.Dimension(508, 344));

        titleDLbl.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        titleDLbl.setForeground(new java.awt.Color(31, 45, 61));
        titleDLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleDLbl.setText("Device Lending & Access Tracker ");

        staffDRB.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        staffDRB.setForeground(new java.awt.Color(31, 45, 61));
        staffDRB.setText("Staff");
        staffDRB.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        staffDRB.setContentAreaFilled(false);
        staffDRB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        staffDRB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        staffDRB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/staff.png"))); // NOI18N
        staffDRB.setIconTextGap(5);
        staffDRB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        staffDRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffDRBActionPerformed(evt);
            }
        });

        borrowerDRB.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        borrowerDRB.setForeground(new java.awt.Color(31, 45, 61));
        borrowerDRB.setText("Borrower");
        borrowerDRB.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        borrowerDRB.setContentAreaFilled(false);
        borrowerDRB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        borrowerDRB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        borrowerDRB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/borrower.png"))); // NOI18N
        borrowerDRB.setIconTextGap(5);
        borrowerDRB.setMaximumSize(new java.awt.Dimension(50, 76));
        borrowerDRB.setMinimumSize(new java.awt.Dimension(50, 76));
        borrowerDRB.setPreferredSize(new java.awt.Dimension(50, 76));
        borrowerDRB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        borrowerDRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowerDRBActionPerformed(evt);
            }
        });

        discDLbl.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        discDLbl.setForeground(new java.awt.Color(107, 124, 147));
        discDLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        discDLbl.setText("Select your role to continue");

        javax.swing.GroupLayout dashBoardLayout = new javax.swing.GroupLayout(dashBoard);
        dashBoard.setLayout(dashBoardLayout);
        dashBoardLayout.setHorizontalGroup(
            dashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashBoardLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(staffDRB, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(borrowerDRB, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(dashBoardLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(discDLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashBoardLayout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(titleDLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        dashBoardLayout.setVerticalGroup(
            dashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashBoardLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(titleDLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(discDLbl)
                .addGap(78, 78, 78)
                .addGroup(dashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(staffDRB, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrowerDRB, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        staffLoginForm.setBackground(new java.awt.Color(232, 244, 253));
        staffLoginForm.setPreferredSize(new java.awt.Dimension(508, 344));

        titleSLbl.setBackground(new java.awt.Color(31, 45, 61));
        titleSLbl.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        titleSLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleSLbl.setText("Staff Login");

        staffIdSLbl.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        staffIdSLbl.setText("Staff ID:");

        nameSLbl.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        nameSLbl.setText("Name:");

        emailSLbl.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        emailSLbl.setText("Email:");

        phoneSLbl.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        phoneSLbl.setText("Phone:");

        staffRoleSLbl.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        staffRoleSLbl.setText("Staff Role:");

        discSLbl.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        discSLbl.setForeground(new java.awt.Color(107, 124, 147));
        discSLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        discSLbl.setText("Enter your Staff Credentials");

        backSBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        backSBtn.setForeground(new java.awt.Color(31, 45, 61));
        backSBtn.setText("Back ");
        backSBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backSBtnActionPerformed(evt);
            }
        });

        LoginSBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LoginSBtn.setForeground(new java.awt.Color(31, 45, 61));
        LoginSBtn.setText("Login");

        javax.swing.GroupLayout staffLoginFormLayout = new javax.swing.GroupLayout(staffLoginForm);
        staffLoginForm.setLayout(staffLoginFormLayout);
        staffLoginFormLayout.setHorizontalGroup(
            staffLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffLoginFormLayout.createSequentialGroup()
                .addGroup(staffLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(staffLoginFormLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(staffLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(staffRoleSLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(phoneSLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(emailSLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nameSLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(staffIdSLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(staffLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(staffIdSTF)
                            .addComponent(nameSTF)
                            .addComponent(emailSTF)
                            .addComponent(phoneSTF, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(roleSTF)))
                    .addGroup(staffLoginFormLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(titleSLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(staffLoginFormLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(discSLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(staffLoginFormLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(backSBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LoginSBtn)
                .addGap(103, 103, 103))
        );
        staffLoginFormLayout.setVerticalGroup(
            staffLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffLoginFormLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(titleSLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(discSLbl)
                .addGap(42, 42, 42)
                .addGroup(staffLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(staffIdSLbl)
                    .addComponent(staffIdSTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(staffLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nameSLbl)
                    .addComponent(nameSTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(staffLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailSLbl)
                    .addComponent(emailSTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(staffLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(phoneSLbl)
                    .addComponent(phoneSTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(staffLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(staffRoleSLbl)
                    .addComponent(roleSTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(staffLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backSBtn)
                    .addComponent(LoginSBtn))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        borrowerLoginForm.setBackground(new java.awt.Color(232, 244, 253));
        borrowerLoginForm.setPreferredSize(new java.awt.Dimension(508, 344));

        titleBLbl.setBackground(new java.awt.Color(31, 45, 61));
        titleBLbl.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        titleBLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleBLbl.setText("Borrower Login");

        userIdBLbl.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        userIdBLbl.setText("User ID:");

        nameBLbl.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        nameBLbl.setText("Name:");

        emailBLbl.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        emailBLbl.setText("Email:");

        phoneBLbl.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        phoneBLbl.setText("Phone:");

        skillLevelBLbl.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        skillLevelBLbl.setText("Skill Level:");

        nameBTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameBTFActionPerformed(evt);
            }
        });

        discBLbl.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        discBLbl.setForeground(new java.awt.Color(107, 124, 147));
        discBLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        discBLbl.setText("Enter your credentials");

        backBBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        backBBtn.setForeground(new java.awt.Color(31, 45, 61));
        backBBtn.setText("Back ");
        backBBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBBtnActionPerformed(evt);
            }
        });

        LoginBBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LoginBBtn.setForeground(new java.awt.Color(31, 45, 61));
        LoginBBtn.setText("Login");

        javax.swing.GroupLayout borrowerLoginFormLayout = new javax.swing.GroupLayout(borrowerLoginForm);
        borrowerLoginForm.setLayout(borrowerLoginFormLayout);
        borrowerLoginFormLayout.setHorizontalGroup(
            borrowerLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borrowerLoginFormLayout.createSequentialGroup()
                .addGroup(borrowerLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(borrowerLoginFormLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(borrowerLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(titleBLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(discBLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(borrowerLoginFormLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(borrowerLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(phoneBLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(emailBLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nameBLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userIdBLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(skillLevelBLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(borrowerLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userIdBTF)
                            .addComponent(nameBTF)
                            .addComponent(emailBTF)
                            .addComponent(phoneBTF, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(skillLevelBTF)))
                    .addGroup(borrowerLoginFormLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(backBBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LoginBBtn)
                        .addGap(77, 77, 77)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        borrowerLoginFormLayout.setVerticalGroup(
            borrowerLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borrowerLoginFormLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(titleBLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(discBLbl)
                .addGap(42, 42, 42)
                .addGroup(borrowerLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userIdBLbl)
                    .addComponent(userIdBTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(borrowerLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nameBLbl)
                    .addComponent(nameBTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(borrowerLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailBLbl)
                    .addComponent(emailBTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(borrowerLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(phoneBLbl)
                    .addComponent(phoneBTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(borrowerLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(skillLevelBLbl)
                    .addComponent(skillLevelBTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(borrowerLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBBtn)
                    .addComponent(LoginBBtn))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(staffLoginForm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(borrowerLoginForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(staffLoginForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(borrowerLoginForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void handleStaffLogin() {
        String userId = staffIdSTF.getText().trim();
        String name = nameSTF.getText().trim();
        String email = emailSTF.getText().trim();
        String phone = phoneSTF.getText().trim();
        String staffRole = roleSTF.getText().trim();
        if (userId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Staff ID is required.", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Name is required.", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Email is required.", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!email.contains("@")) {
            JOptionPane.showMessageDialog(this, "Email must contain @.", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!phone.isEmpty() && !phone.matches("[0-9]+")) {
            JOptionPane.showMessageDialog(this, "Phone must contain only digits (0-9).", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!phone.isEmpty() && phone.length() != 10) {
            JOptionPane.showMessageDialog(this, "Phone must be 10 digits long.", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }
        currentStaff = new Staff(userId, name, email, phone, staffRole);
        currentBorrower = null;
        JOptionPane.showMessageDialog(this, "Welcome, " + name + " (Staff).");
        dashBoard.setVisible(true);
        staffLoginForm.setVisible(false);
        borrowerLoginForm.setVisible(false);
    }

    private void handleBorrowerLogin() {
        String userId = userIdBTF.getText().trim();
        String name = nameBTF.getText().trim();
        String email = emailBTF.getText().trim();
        String phone = phoneBTF.getText().trim();
        String skillLevel = skillLevelBTF.getText().trim();
        if (userId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "User ID is required.", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Name is required.", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Email is required.", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!email.contains("@")) {
            JOptionPane.showMessageDialog(this, "Email must contain @.", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!phone.isEmpty() && !phone.matches("[0-9]+")) {
            JOptionPane.showMessageDialog(this, "Phone must contain only digits (0-9).", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!phone.isEmpty() && phone.length() != 10) {
            JOptionPane.showMessageDialog(this, "Phone must be 10 digits long.", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int maxActiveLoan = 3;
        try {
            if (!skillLevel.isEmpty()) {
                maxActiveLoan = Math.max(1, Integer.parseInt(skillLevel));
            }
        } catch (NumberFormatException ex) {
        }
        currentBorrower = new Borrower(userId, name, email, phone, skillLevel, maxActiveLoan);
        currentStaff = null;
        JOptionPane.showMessageDialog(this, "Welcome, " + name + " (Borrower).");
        dashBoard.setVisible(true);
        staffLoginForm.setVisible(false);
        borrowerLoginForm.setVisible(false);
    }
    private void staffDRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffDRBActionPerformed
        // TODO add your handling code here:
        dashBoard.setVisible(false);
        staffLoginForm.setVisible(true);
        borrowerLoginForm.setVisible(false);
    }//GEN-LAST:event_staffDRBActionPerformed

    private void nameBTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameBTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameBTFActionPerformed

    private void borrowerDRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowerDRBActionPerformed
        // TODO add your handling code here:
        dashBoard.setVisible(false);
        staffLoginForm.setVisible(false);
        borrowerLoginForm.setVisible(true);
    }//GEN-LAST:event_borrowerDRBActionPerformed

    private void backSBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backSBtnActionPerformed
        // TODO add your handling code here:
        dashBoard.setVisible(true);
        staffLoginForm.setVisible(false);
        borrowerLoginForm.setVisible(false);
    }//GEN-LAST:event_backSBtnActionPerformed

    private void backBBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBBtnActionPerformed
        // TODO add your handling code here:
        dashBoard.setVisible(true);
        staffLoginForm.setVisible(false);
        borrowerLoginForm.setVisible(false);
    }//GEN-LAST:event_backBBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIApp().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginBBtn;
    private javax.swing.JButton LoginSBtn;
    private javax.swing.JButton backBBtn;
    private javax.swing.JButton backSBtn;
    private javax.swing.JRadioButton borrowerDRB;
    private javax.swing.JPanel borrowerLoginForm;
    private javax.swing.JPanel dashBoard;
    private javax.swing.JLabel discBLbl;
    private javax.swing.JLabel discDLbl;
    private javax.swing.JLabel discSLbl;
    private javax.swing.JLabel emailBLbl;
    private javax.swing.JTextField emailBTF;
    private javax.swing.JLabel emailSLbl;
    private javax.swing.JTextField emailSTF;
    private javax.swing.ButtonGroup loginRB;
    private javax.swing.JLabel nameBLbl;
    private javax.swing.JTextField nameBTF;
    private javax.swing.JLabel nameSLbl;
    private javax.swing.JTextField nameSTF;
    private javax.swing.JLabel phoneBLbl;
    private javax.swing.JTextField phoneBTF;
    private javax.swing.JLabel phoneSLbl;
    private javax.swing.JTextField phoneSTF;
    private javax.swing.JTextField roleSTF;
    private javax.swing.JLabel skillLevelBLbl;
    private javax.swing.JTextField skillLevelBTF;
    private javax.swing.JRadioButton staffDRB;
    private javax.swing.JLabel staffIdSLbl;
    private javax.swing.JTextField staffIdSTF;
    private javax.swing.JPanel staffLoginForm;
    private javax.swing.JLabel staffRoleSLbl;
    private javax.swing.JLabel titleBLbl;
    private javax.swing.JLabel titleDLbl;
    private javax.swing.JLabel titleSLbl;
    private javax.swing.JLabel userIdBLbl;
    private javax.swing.JTextField userIdBTF;
    // End of variables declaration//GEN-END:variables
}
